replicaCount: 3

image:
  zookeeper:
    repository: bitnami/zookeeper
    tag: latest
  kafka:
    repository: bitnami/kafka
    tag: latest

service:
  zookeeper:
    clientPort: 2181
    followerPort: 2888
    leaderPort: 3888
  kafka:
    port: 9092

volumeClaimTemplates:
  zookeeper:
    storage:
      size: 5Gi
  kafka:
    storage:
      size: 5Gi

env:
  kafka:
   data:
    KAFKA_CFG_ZOOKEEPER_CONNECT: crs-zookeeper-0.zookeeper-cluster.default.svc.cluster.local:2181,crs-zookeeper-1.zookeeper-cluster.default.svc.cluster.local:2181,crs-zookeeper-2.zookeeper-cluster.default.svc.cluster.local:2181
    ALLOW_PLAINTEXT_LISTENER: "yes"
