replicaCount: 3

image:
  zookeeper:
    repository: bitnami/zookeeper
    tag: latest
  kafka:
    repository: bitnami/kafka
    tag: latest

service:
  zookeeper:
    clientPort: 2181
    followerPort: 2888
    leaderPort: 3888
  kafka:
    port: 9092
    internalport: 29092
    nodePort: 30092

volumeClaimTemplates:
  zookeeper:
    storage:
      size: 5Gi
  kafka:
    storage:
      size: 5Gi

env:
  kafka:
    advertisedListeners: "INTERNAL://:29092,LISTENER_EXTERNAL://:9092"
    autoCreateTopicsEnable: "true"
    interBrokerListenerName: "INTERNAL"
    listeners: "INTERNAL://:29092,LISTENER_EXTERNAL://:9092"
    listenerSecurityProtocolMap: "INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
    zookeeperConnect: "crs-zookeeper-0.zookeeper-cluster.default.svc.cluster.local:2181,crs-zookeeper-1.zookeeper-cluster.default.svc.cluster.local:2181,crs-zookeeper-2.zookeeper-cluster.default.svc.cluster.local:2181"
    allowPlaintextListener: "yes"
