replicaCount: 3
namespace: kafka
image:
  repository: zookeeper
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    storage: 5Gi

storageClass: gp2

service:
  type: ClusterIP
  port: 2181

env:
  ZOOKEEPER_CLIENT_PORT: 2181
  ZOOKEEPER_TICK_TIME: 2000

