apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: external
      port: {{ .Values.service.kafka.port }}
      targetPort: 9092

    - name: internal
      port: 29092
      targetPort: 29092

  selector:
    app: kafka
  type: {{ .Values.service.kafka.type }}
