apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "kafka"
  replicas: {{ .Values.replicaCount.kafka }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.image.kafka.repository }}:{{ .Values.image.kafka.tag }}"
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-env-config
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/
  
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .values.storageClass }}
        resources:
          requests:
            storage: 5Gi
