apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crs-kafka
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: kafka-cluster
  selector:
    matchLabels:
      app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      hostname: kafka
      containers:
      - name: kafka
        image: "{{ .Values.image.kafka.repository }}:{{ .Values.image.kafka.tag }}"
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: {{ .Values.service.kafka.port }}
        - containerPort: {{ .Values.service.kafka.internalport }}
        envFrom:
        - configMapRef:
            name: kafka-env-config
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.volumeClaimTemplates.kafka.storage.size }}
