apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-env-config
data:
  KAFKA_ADVERTISED_LISTENERS: "{{ .Values.env.kafka.advertisedListeners }}"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "{{ .Values.env.kafka.autoCreateTopicsEnable }}"
  KAFKA_INTER_BROKER_LISTENER_NAME: "{{ .Values.env.kafka.interBrokerListenerName }}"
  KAFKA_LISTENERS: "{{ .Values.env.kafka.listeners }}"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "{{ .Values.env.kafka.listenerSecurityProtocolMap }}"
  KAFKA_CFG_ZOOKEEPER_CONNECT: "{{ .Values.env.kafka.zookeeperConnect }}"
  ALLOW_PLAINTEXT_LISTENER: "{{ .Values.env.kafka.allowPlaintextListener }}"
