apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-cluster
  ports:
    - name: internal
      port: {{ .Values.service.kafka.internalport }}
      targetPort: {{ .Values.service.kafka.internalport }}  
    - name: external
      port: {{ .Values.service.kafka.port }}
      targetPort: {{ .Values.service.kafka.port }}
      nodePort: {{ .Values.service.kafka.nodePort }}
  type: NodePort

