apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "zookeeper"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.env.ZOOKEEPER_CLIENT_PORT }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "{{ .Values.env.ZOOKEEPER_TICK_TIME }}"
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storageClass }}
        resources:
          requests:
            storage: {{ .Values.resources.requests.storage }}

