apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
spec:
  selector:
    app: zookeeper-cluster
  ports:
    - name: client
      port: {{ .Values.service.zookeeper.clientPort }}
      targetPort: {{ .Values.service.zookeeper.clientPort }}
    - name: follower
      port: {{  .Values.service.zookeeper.followerPort }}
      targetPort: {{  .Values.service.zookeeper.followerPort }}
    - name: leader
      port: {{  .Values.service.zookeeper.leaderPort }}
      targetPort: {{  .Values.service.zookeeper.leaderPort }}
  clusterIP: None
