apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .values.storageClass }}
  resources:
    requests:
      storage: 5Gi

