apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "zookeeper"
  replicas: {{ .Values.replicaCount.zookeeper }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.image.zookeeper.repository }}:{{ .Values.image.zookeeper.tag }}"
          
          ports:
            - containerPort: {{ .Values.service.zookeeper.port }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.env.zookeeper.ZOOKEEPER_CLIENT_PORT }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "{{ .Values.env.zookeeper.ZOOKEEPER_TICK_TIME }}"
            - name: ZOO_SERVERS
              value: "zookeeper-0.zookeeper.{{ .Values.namespace}}.svc.local:2888:3888,zookeeper-1.zookeeper.{{ .Values.namespace}}.svc.local:2888:3888,zookeeper-2.zookeeper.{{ .Values.namespace}}.svc.local:2888:3888"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
  
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storageClass }}
        resources:
          requests:
            storage: {{ .Values.resources.zookeeper.requests.storage }}

