apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
spec:
  selector:
    app: zookeeper-cluster
  ports:
    - name: client
      port: {{ .Values.zookeeper.ports.client }}
      targetPort: {{ .Values.zookeeper.ports.client }}
    - name: follower
      port: {{ .Values.zookeeper.ports.follower }}
      targetPort: {{ .Values.zookeeper.ports.follower }}
    - name: leader
      port: {{ .Values.zookeeper.ports.leader }}
      targetPort: {{ .Values.zookeeper.ports.leader }}
  clusterIP: None
